env:
  es6: true
  node: true

ignorePatterns:
  - dist
  - node_modules
  - "*.js"
  - "*.d.ts"

extends:
  - plugin:@lichtblick/base
  - plugin:prettier/recommended

rules:
  "@lichtblick/license-header": ["error", { licenseType: "MPL-2.0" }]
  prettier/prettier: error

overrides:
  - files: ["*.ts"]
    extends:
      - plugin:@lichtblick/typescript
    parserOptions:
      project: ./tsconfig.json
    rules:
      "@typescript-eslint/explicit-member-accessibility": error
      "@typescript-eslint/no-explicit-any": warn
      "@typescript-eslint/no-unused-vars":
        - error
        - vars: all
          args: after-used
          varsIgnorePattern: "^_."
          argsIgnorePattern: "^_."

  - files: ["**/*.test.ts"]
    extends:
      - plugin:@lichtblick/typescript
    parserOptions:
      project: ./tsconfig.test.json
    env:
      jest: true

  - files: ["src/builders/**/*.ts", "src/utilities.ts"]
    rules:
      "@typescript-eslint/restrict-template-expressions": off
      "@typescript-eslint/no-extraneous-class": off
      "@typescript-eslint/unbound-method": off
      "@typescript-eslint/no-unnecessary-type-parameters": off
      "@typescript-eslint/no-unsafe-return": off
